#!/usr/bin/env python3

# simple script to generate a password, only supports adding new users

import sys
import os
import crypt
import getpass

users = open('users', 'r').readlines()
users = dict(user.strip().split(',',1) for user in users)

user = sys.argv[1]

if user in users:
	print(f'User "{user}" already present')
	sys.exit(0)

pass1 = getpass.getpass('Password: ')
pass2 = getpass.getpass('Verify: ')

if pass1 != pass2:
	print(f'Passwords do not match')
	sys.exit(0)

password = crypt.crypt(pass1)

fp = open('users', 'a')
fp.write(f'{user},{password}\n')
